### ISSUE TITLE
fix: main does not compile -- watch/gates.rs test passes "medium" str where create_card takes Priority enum (#632 x #633 semantic merge conflict)

### ISSUE THREAD

**Issue by ssilvius** [ssilvius/legion#634]
Two green PRs (#632 watch/ carve, #633 Priority enum on kanban::create_card) merged within minutes; each passed CI against its own merge-base, but the combination is a type error -- a semantic merge conflict with zero textual conflict.

**Symptom:** `cargo check --all-targets` on main fails:
```
error[E0308]: mismatched types
  --> src/watch/gates.rs:700:13
   |  expected `Priority`, found `&str`
```

**Fix:** in the `blocked_card` test helper in src/watch/gates.rs, pass `crate::kanban::Priority::Med` instead of `"medium"`. (Note: "medium" was never a valid Priority string -- the FromStr set is low/med/high/critical -- so the enum migration also caught a latent test bug.)

**Acceptance criteria:**
- [ ] `cargo check --all-targets` passes on the branch
- [ ] `cargo test` passes
- [ ] `cargo clippy --all-targets -- -D warnings` passes
- [ ] `cargo fmt -- --check` passes

Coordination note: both stranded 2d worktree branches (refactor/612-comms, refactor/613-serve) carry this same fix as commit 1; once this lands they rebase and drop the duplicate.

**Comment by ssilvius** [comment]
Groom 2026-07-05, closing as fixed: main compiles clean -- full suite green on 3939cba.
